# Generated by Django 5.2.6 on 2025-10-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('minutes', models.IntegerField()),
                ('source', models.CharField(default='manual', max_length=20)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'train_record',
                'indexes': [models.Index(fields=['user_id', 'date'], name='train_recor_user_id_41c64d_idx')],
            },
        ),
    ]
