# Generated by Django 5.2.6 on 2025-12-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('admin_comment', models.CharField(blank=True, max_length=500, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('decision_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leave_request',
                'indexes': [models.Index(fields=['user_id', 'start_date'], name='leave_reque_user_id_82ecb5_idx'), models.Index(fields=['status', 'start_date'], name='leave_reque_status_6a5f3d_idx')],
            },
        ),
    ]
