# Generated by Django 5.2.6 on 2025-12-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainrecord',
            name='violation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainrecord',
            name='violation_times',
            field=models.IntegerField(default=0),
        ),
    ]
