# Generated by Django 5.2.6 on 2025-12-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_train_record_add_unique_user_date'),
        ('business', '0003_trainrecord_violation_reason_and_more'),
    ]

    operations = [
    ]
