# Generated by Django 5.2.6 on 2025-12-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_merge_20251215_2130'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trainrecord',
            name='idx_train_record_date_user',
        ),
    ]
