# Generated by Django 5.2.6 on 2025-12-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_captchachallenge_sysuser_student_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='violation_count',
            field=models.IntegerField(default=0, verbose_name='违规次数'),
        ),
    ]
