# Generated by Django 5.2.6 on 2025-09-25 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysrolemenu',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.sysrole'),
        ),
    ]
