# Generated by Django 5.2.6 on 2025-10-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='update_time',
            field=models.DateField(null=True, verbose_name='更新时间'),
        ),
    ]
