# Generated by Django 5.2.6 on 2025-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAuthConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trust_code_cipher', models.TextField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_auth_config',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSyncState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('default_backfill_days', models.IntegerField(default=30)),
                ('safety_buffer_minutes', models.IntegerField(default=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_sync_state',
            },
        ),
        migrations.CreateModel(
            name='AttendanceCheckin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('org_id', models.CharField(blank=True, max_length=50, null=True)),
                ('student_no', models.CharField(db_index=True, max_length=50)),
                ('check_in_time_ms', models.BigIntegerField(db_index=True)),
                ('check_in_time', models.DateTimeField(db_index=True)),
                ('checkin_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_checkin',
                'indexes': [models.Index(fields=['student_no', 'check_in_time'], name='attendance__student_8a30f1_idx'), models.Index(fields=['check_in_time'], name='attendance__check_i_1c112a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSyncJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('partial', 'partial')], default='queued', max_length=20)),
                ('range_start', models.DateTimeField(blank=True, null=True)),
                ('range_end', models.DateTimeField(blank=True, null=True)),
                ('cursor_day', models.DateField(blank=True, null=True)),
                ('cursor_page', models.IntegerField(default=1)),
                ('inserted_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_sync_job',
                'indexes': [models.Index(fields=['status', 'create_time'], name='attendance__status_888779_idx'), models.Index(fields=['range_start', 'range_end'], name='attendance__range_s_d84f90_idx')],
            },
        ),
    ]
